DROP TABLE CUSTOMER PURGE;
CREATE TABLE CUSTOMER(CUST_ID VARCHAR2(5)PRIMARY KEY CONSTRAINT CUST_ID_CHK_C CHK(CUST_ID LIKE 'C___'),
            NAME VARCHAR2(10) NOT NULL CONSTRAINT CUST_NAME_CHK_DS CHECK(SUBSTR(NAME,1,1)BETWEEN 'D' AND 'S'),
            EMAIL VARCHAR2(30) UNIQUE CONSTRAINT EMAIL_CHK CHECK(EMAIL LIKE '__%@_%._'),
            CITY VARCHAR2(15) CONSTRAINT CITY_CHK CHECK(UPPER(CITY)IN('RAJKOT','SURAT','AHMEDABAD','VADODARA'))
);

INSERT INTO CUSTOMER VALUES('C1234','DABC','JAINISH.BARBHAYA@GMAIL.IN','RAJKOT');
INSERT INTO CUSTOMER VALUES('C1235','DABD','JAINISH.BARBHAYA@GMAIL.IN','SURAT');